# Use the official PostgreSQL image from the Docker Hub
FROM postgres:13

# Set environment variables for the database
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=database

# Expose the PostgreSQL port
EXPOSE 5432
