apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: my-app
